server:
  port: 31501
  servlet:
    context-path: /

spring:
  datasource:
    dynamic:
      primary: mysql
      datasource:
        mysql:
          url: jdbc:mysql://${mysql.ip}:${mysql.port}/${mysql.dbname}?serverTimezone=Asia/Shanghai
          username: ${mysql.username}
          password: ${mysql.password}
          driver-class-name: com.mysql.cj.jdbc.Driver
          druid:
            initial-size: 20
            min-idle: 20
            max-active: 50
            max-wait: 60000
            validation-query: select 1
  rest:
    connect-time-out: 30000  # 建立连接的超时时间
    connect-request-time-out: 5000 #从连接池获取到连接的超时时间
    socket-time-out: 30000 #指客户端和服务进行数据交互的时间，是指两者之间如果两个数据包之间的时间大于该时间则认为超时
    max-conn-total: 600 # 连接池总数
    max-conn-per-rout: 60 # 每个路由最大链接数

  #在SpringBoot2.6之后，Spring MVC 处理程序映射匹配请求路径的默认策略已从 AntPathMatcher 更改为PathPatternParser
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

#mybatis扫描路径
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/**/*Mapper.xml

#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql



